# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 431e715825fce23c7a6e092fb1b5411c3221dc3ce253274891e5b2533359a0bca52296c2f83651ef286ee4b98b30a515b85762c058582c7c6de48b710f51ca1c

test:
  secret_key_base: 0d0454e4a5b1d7a4c07c7bcc61a37a266b7798e4b560c99093b044061ae3f6991ef7ead59181eb69675a63dfcef05aee2e0bb34befee69da7087a1572a569a15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
